[platformio]
default_envs = waveshare_esp32s3_touch_lcd_1_85

[env:waveshare_esp32s3_touch_lcd_1_85]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = waveshare_esp32_s3_touch_lcd_1_85
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    lvgl/lvgl@8.3.10
    moononournation/GFX Library for Arduino@^1.5.3

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I include

board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

